---
- name: Install nano, wget, git, ntp, net-tools
  yum: name={{ item }} state=present
  with_items:
    - nano
    - wget
    - git
    - ntp
    - net-tools

- name: Set timezone
  command: "timedatectl set-timezone Europe/Amsterdam"

- name: Enable and start ntpd
  service: name=ntpd enabled=yes state=started

- name: Enable and start firewalld
  service: name=firewalld enabled=yes state=started

- name: Disable SELinux
  selinux: state=disabled