---
- name: Installing PHP 7.0 with Extensions
  yum: name={{ item }} state=present
  with_items:
      - php70w
      - php70w-bcmath
      - php70w-cli
      - php70w-common
      - php70w-devel
      - php70w-fpm
      - php70w-gd
      - php70w-intl
      - php70w-mbstring
      - php70w-mcrypt
      - php70w-mysqlnd
      - php70w-pdo
      - php70w-pear
#      - php70w-pecl-xdebug
#      - php70w-pecl-redis
      - php70w-pecl-imagick
      - php70w-soap
      - php70w-xml


#- name: Start and Enable Services
#  service: name=php-fpm enabled=yes
#  service: name=php-fpm state=started
